_home:
    path: /
    defaults: { _controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction', route: _dashboard, permanent: true }

_view_quote_external:
    path: '/view/quote/{uuid}'
    defaults: { _controller: 'SolidInvoice\CoreBundle\Action\ViewBilling::quoteAction' }
    requirements:
        uuid: '[a-zA-Z0-9-]{36}'

_view_invoice_external:
    path: '/view/invoice/{uuid}'
    defaults: { _controller: 'SolidInvoice\CoreBundle\Action\ViewBilling::invoiceAction' }
    requirements:
        uuid: '[a-zA-Z0-9-]{36}'

_select_company:
    path: '/select-company'
    defaults: { _controller: 'SolidInvoice\CoreBundle\Action\SelectCompany' }

_switch_company:
    path: '/select-company/{id}'
    defaults: { _controller: 'SolidInvoice\CoreBundle\Action\SelectCompany::switchCompany' }

_create_company:
    path: '/create-company'
    defaults: { _controller: 'SolidInvoice\CoreBundle\Action\CreateCompany' }
