apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "solidinvoice.fullname" . }}
  labels:
    {{- include "solidinvoice.labels" . | nindent 4 }}
data:
  SOLIDINVOICE_ENV: "prod"
  SOLIDINVOICE_DEBUG: "0"
  SOLIDINVOICE_DOCKER: "true"
  SOLIDINVOICE_CONFIG_DIR: "/etc/solidinvoice"
  SOLIDINVOICE_LOCALE: {{ .Values.app.locale | quote }}
  SOLIDINVOICE_ALLOW_REGISTRATION: {{ .Values.app.allowRegistration | toString | quote }}
  SOLIDINVOICE_MAILER_SENDER: {{ .Values.mailer.sender | quote }}
  {{- if .Values.sentry.enabled }}
  SOLIDINVOICE_SENTRY_RELEASE: {{ default .Chart.AppVersion .Values.image.tag | quote }}
  SOLIDINVOICE_SENTRY_SEND_DEFAULT_PII: "false"
  {{- end }}
  {{- if .Values.app.workerMode }}
  FRANKENPHP_WORKER_MODE: "1"
  {{- end }}
