security:
    password_hashers:
        SolidInvoice\UserBundle\Entity\User:
            algorithm: auto
    role_hierarchy:
        ROLE_ADMIN: null
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
        ROLE_CLIENT: ROLE_USER
        ROLE_USER: null
    providers:
        solidinvoice_user:
            entity:
                class: SolidInvoice\UserBundle\Entity\User
        api_token_user_provider:
            id: 'SolidInvoice\ApiBundle\Security\Provider\ApiTokenUserProvider'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_doc:
            pattern: ^/api/docs
            anonymous: true
            lazy: true
        api_login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            form_login:
                provider: api_token_user_provider
                check_path: /api/login
                require_previous_session: false
                success_handler: 'SolidInvoice\ApiBundle\Event\Listener\AuthenticationSuccessHandler'
                failure_handler: 'SolidInvoice\ApiBundle\Event\Listener\AuthenticationFailHandler'
        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators: ['SolidInvoice\ApiBundle\Security\ApiTokenAuthenticator']
            provider: api_token_user_provider
        installer:
            pattern: '^/install(.*)'
            anonymous: true
            lazy: true
        external:
            pattern: '^/view/(quote|invoice)/([a-zA-Z0-9-]{36})'
            anonymous: true
            lazy: true
            context: frontend
        create:
            pattern: '^/payments/create/([a-zA-Z0-9-]{36})'
            anonymous: true
            lazy: true
            context: frontend
        capture:
            pattern: '^/payment/(capture|notify|done)/(.*)'
            anonymous: true
            lazy: true
            context: frontend
        done:
            pattern: ^/payments/done$
            anonymous: true
            lazy: true
            context: frontend
        login:
            pattern: ^/(login|register)$
            anonymous: true
            lazy: true
        accept_invite:
            pattern: ^/invite/accept/([a-zA-Z0-9-]{36})$
            anonymous: true
            lazy: true
        password_reset:
            pattern: '^/forgot-password(.*)'
            anonymous: true
            lazy: true
        main:
            remember_me:
                secret: '%env(secret)%'
                lifetime: 3600
                path: /
                domain: null
            pattern: ^/
            context: frontend
            form_login:
                provider: solidinvoice_user
                csrf_token_generator: security.csrf.token_manager
                check_path: /login-check
                login_path: /login
                always_use_default_target_path: true
                default_target_path: /select-company
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: '^/view/(quote|invoice)/([a-zA-Z0-9-]{36})$', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/install(.*)', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Invitation
        - { path: '^/invite/accept/([a-zA-Z0-9-]{36})$', roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # payments
        - { path: '^/payments/create/([a-zA-Z0-9-]{36})$', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/payment/capture/(.*), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/payments/done$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
