<?php

declare(strict_types=1);

/*
 * This file is part of SolidInvoice project.
 *
 * (c) Pierre du Plessis <open-source@solidworx.co>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

// !! This file is autogenerated. Do not edit. !!

namespace SolidInvoice\NotificationBundle\Configurator;

use SolidInvoice\NotificationBundle\Form\Type\Transport\EsendexType;
use Symfony\Component\Notifier\Transport\Dsn;
use function sprintf;

/**
 * @codeCoverageIgnore
 */
final class EsendexConfigurator implements ConfiguratorInterface
{
    public static function getName(): string
    {
        return 'Esendex';
    }

    public static function getType(): string
    {
        return 'texter';
    }

    public function getForm(): string
    {
        return EsendexType::class;
    }

    /**
     * @param array{ user_name: string, password: string, account_reference: string, from: string } $config
     */
    public function configure(array $config): Dsn
    {
        return new Dsn(sprintf('esendex://%s:%s@default?accountreference=%s&amp;from=%s', $config['user_name'], $config['password'], $config['account_reference'], $config['from']));
    }
}
