<?php

declare(strict_types=1);

/*
 * This file is part of SolidInvoice project.
 *
 * (c) Pierre du Plessis <open-source@solidworx.co>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

// !! This file is autogenerated. Do not edit. !!

namespace SolidInvoice\NotificationBundle\Configurator;

use SolidInvoice\NotificationBundle\Form\Type\Transport\FreeMobileType;
use Symfony\Component\Notifier\Transport\Dsn;
use function sprintf;

final class FreeMobileConfigurator implements ConfiguratorInterface
{
    public static function getName(): string
    {
        return 'FreeMobile';
    }

    public static function getType(): string
    {
        return 'texter';
    }

    public function getForm(): string
    {
        return FreeMobileType::class;
    }

    /**
     * @param array{ login: string, api_key: string, phone: string } $config
     */
    public function configure(array $config): Dsn
    {
        return new Dsn(sprintf('freemobile://%s:%s@default?phone=%s', $config['login'], $config['api_key'], $config['phone']));
    }
}
