<?php

declare(strict_types=1);

/*
 * This file is part of SolidInvoice project.
 *
 * (c) Pierre du Plessis <open-source@solidworx.co>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

// !! This file is autogenerated. Do not edit. !!

namespace SolidInvoice\NotificationBundle\Configurator;

use SolidInvoice\NotificationBundle\Form\Type\Transport\SendinblueType;
use Symfony\Component\Notifier\Transport\Dsn;
use function sprintf;

/**
 * @codeCoverageIgnore
 */
final class SendinblueConfigurator implements ConfiguratorInterface
{
    public static function getName(): string
    {
        return 'Sendinblue';
    }

    public static function getType(): string
    {
        return 'texter';
    }

    public function getForm(): string
    {
        return SendinblueType::class;
    }

    /**
     * @param array{ api_key: string, phone: string } $config
     */
    public function configure(array $config): Dsn
    {
        return new Dsn(sprintf('sendinblue://%s@default?sender=%s', $config['api_key'], $config['phone']));
    }
}
