services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SolidInvoice\UserBundle\Repository\ApiTokenRepository:
        tags: ['doctrine.repository_service']

    SolidInvoice\UserBundle\Repository\ApiTokenHistoryRepository:
        tags: ['doctrine.repository_service']

    SolidInvoice\UserBundle\Repository\UserRepository:
        tags: ['doctrine.repository_service']

    SolidInvoice\UserBundle\Repository\UserInvitationRepository:
        tags: ['doctrine.repository_service']

    SolidInvoice\UserBundle\Repository\UserRepositoryInterface: '@SolidInvoice\UserBundle\Repository\UserRepository'

    # Fixtures
    SolidInvoice\UserBundle\DataFixtures\ORM\:
        resource: '%kernel.project_dir%/src/UserBundle/DataFixtures/ORM/*'
        tags: ['doctrine.fixture.orm']

    SolidInvoice\UserBundle\UserInvitation\UserInvitation: ~
