<?php

declare(strict_types=1);

/*
 * This file is part of SolidInvoice project.
 *
 * (c) Pierre du Plessis <open-source@solidworx.co>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace SolidInvoice\ApiBundle\Tests\Functional\Webhook;

use SolidInvoice\ApiBundle\Entity\Webhook;
use SolidInvoice\ApiBundle\Test\ApiTestCase;
use SolidInvoice\ApiBundle\Test\Factory\WebhookFactory;
use SolidInvoice\CoreBundle\Company\CompanySelector;
use SolidInvoice\CoreBundle\Test\Factory\CompanyFactory;
use Symfony\Component\Uid\Ulid;
use Zenstruck\Foundry\Test\Factories;

/**
 * @group functional
 */
final class WebhookTest extends ApiTestCase
{
    use Factories;

    protected function getResourceClass(): string
    {
        return Webhook::class;
    }

    public function testCreate(): void
    {
        $data = [
            'url' => 'https://example.com/webhook',
            'events' => ['invoice.created'],
            'active' => true,
        ];

        $result = $this->requestPost('/api/webhooks', $data);

        self::assertArrayHasKey('id', $result);
        self::assertTrue(Ulid::isValid($result['id']));
        self::assertArrayHasKey('secret', $result);
        self::assertNotEmpty($result['secret']);
        unset($result['id'], $result['@id'], $result['secret']);

        self::assertEqualsCanonicalizing([
            '@context' => $this->getContextForResource(Webhook::class),
            '@type' => 'Webhook',
            'url' => 'https://example.com/webhook',
            'events' => ['invoice.created'],
            'active' => true,
        ], $result);
    }

    public function testGet(): void
    {
        $webhook = WebhookFactory::createOne([
            'url' => 'https://example.com/webhook',
            'events' => ['invoice.created'],
            'active' => true,
        ])->_real();

        $data = $this->requestGet($this->getIriFromResource($webhook));

        self::assertEqualsCanonicalizing([
            '@context' => $this->getContextForResource($webhook),
            '@id' => $this->getIriFromResource($webhook),
            '@type' => 'Webhook',
            'id' => $webhook->getId()->toString(),
            'url' => $webhook->getUrl(),
            'events' => $webhook->getEvents(),
            'secret' => $webhook->getSecret(),
            'active' => $webhook->isActive(),
        ], $data);
    }

    public function testEdit(): void
    {
        $webhook = WebhookFactory::createOne([
            'url' => 'https://example.com/webhook',
            'events' => ['invoice.created'],
            'active' => true,
        ])->_real();

        $data = $this->requestPatch(
            $this->getIriFromResource($webhook),
            [
                'url' => 'https://example.com/updated-webhook',
                'active' => false,
            ]
        );

        self::assertEqualsCanonicalizing([
            '@context' => $this->getContextForResource($webhook),
            '@id' => $this->getIriFromResource($webhook),
            '@type' => 'Webhook',
            'id' => $webhook->getId()->toString(),
            'url' => 'https://example.com/updated-webhook',
            'events' => $webhook->getEvents(),
            'secret' => $webhook->getSecret(),
            'active' => false,
        ], $data);
    }

    public function testDelete(): void
    {
        $webhook = WebhookFactory::createOne()->_real();

        $this->requestDelete($this->getIriFromResource($webhook));
    }

    public function testGetCollection(): void
    {
        WebhookFactory::createMany(3);

        $data = $this->requestGetCollection('/api/webhooks');

        self::assertArraySubset([
            '@context' => $this->getContextForResource(Webhook::class),
            '@id' => '/api/webhooks',
            '@type' => 'Collection',
        ], $data);
    }

    public function testSecretAutoGenerated(): void
    {
        $data = [
            'url' => 'https://example.com/webhook',
            'events' => ['invoice.created'],
            'active' => true,
        ];

        $result = $this->requestPost('/api/webhooks', $data);

        self::assertArrayHasKey('secret', $result);
        self::assertNotEmpty($result['secret']);

        $originalSecret = $result['secret'];
        $webhookIri = $result['@id'];

        // Try to PATCH with a 'secret' field — it should be ignored (read-only)
        $patched = $this->requestPatch(
            $webhookIri,
            [
                'secret' => 'new-secret-value',
            ]
        );

        self::assertSame($originalSecret, $patched['secret'], 'Secret should be read-only and not change via PATCH');
    }

    public function testCannotAccessWebhookFromDifferentCompany(): void
    {
        $otherCompany = CompanyFactory::new()->create();
        self::getContainer()->get(CompanySelector::class)->switchCompany($otherCompany->getId());
        $webhook = WebhookFactory::createOne(['company' => $otherCompany])->_real();
        self::getContainer()->get(CompanySelector::class)->switchCompany($this->company->getId());

        $response = self::$client->request('GET', $this->getIriFromResource($webhook), [
            'headers' => [
                'content-type' => 'application/ld+json',
                'accept' => 'application/ld+json',
            ],
        ]);

        self::assertResponseStatusCodeSame(404);
    }
}
