services:
    _defaults:
        public: false
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Gedmo\Timestampable\TimestampableListener:
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
