services:
    _defaults:
        tags: ['form.handler']

    _instanceof:
        SolidWorx\FormHandler\FormHandlerInterface:
            autowire: true
            public: false

    SolidInvoice\CoreBundle\Form\Handler\:
        resource: '../../../Form/Handler'
