services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SolidInvoice\InvoiceBundle\Message\Handler\:
        resource: '../../../Message/Handler'
        arguments:
            $invoiceStateMachine: '@state_machine.invoice'
