<?php

declare(strict_types=1);

/*
 * This file is part of SolidInvoice project.
 *
 * (c) Pierre du Plessis <open-source@solidworx.co>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\MySQLPlatform;
use Doctrine\DBAL\Platforms\OraclePlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version30000_13 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Increase totp_secret column length to 255 to accommodate longer TOTP secrets generated by scheb/2fa-totp';
    }

    public function isTransactional(): bool
    {
        return ! $this->platform instanceof MySQLPlatform && ! $this->platform instanceof OraclePlatform;
    }

    public function up(Schema $schema): void
    {
        $schema->getTable('users')->modifyColumn('totp_secret', ['length' => 255]);
    }

    public function down(Schema $schema): void
    {
        $schema->getTable('users')->modifyColumn('totp_secret', ['length' => 45]);
    }
}
