apiVersion: v2
name: solidinvoice
description: Simple and elegant open-source invoicing application
type: application
icon: https://solidinvoice.co/logo.png
version: 1.0.0
appVersion: "3.0.0"

dependencies:
  - name: mysql
    version: "11.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled

  - name: postgresql
    version: "15.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: redis
    version: "19.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: meilisearch
    version: "0.x.x"
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    condition: meilisearch.enabled
