services:
    _defaults:
        autoconfigure: true
        autowire: true

    SolidInvoice\CronBundle\Command\CronRunCommand: ~
    SolidInvoice\CronBundle\EventSubscriber\CronScheduleEventSubscriber: ~
