FROM dunglas/frankenphp:static-builder-musl

ARG PHP_VERSION=8.3.0
ARG SOLIDINVOICE_VERSION=dev

RUN curl -fsSL https://bun.sh/install | bash \
    apk add --no-cache \
        php84-simplexml

ENV BUN_INSTALL="~/.bun"
ENV PATH="$BUN_INSTALL/bin:$PATH"

COPY --link ./scripts ./scripts
COPY --link ./composer.json ./composer.json
COPY --link ./composer.lock ./composer.lock

RUN scripts/build_binary.sh $SOLIDINVOICE_VERSION
