FROM dunglas/frankenphp:static-builder-musl

ARG PHP_VERSION=8.3.0
ARG SOLIDINVOICE_VERSION=dev

RUN curl -fsSL https://bun.sh/install | bash

ENV BUN_INSTALL="$HOME/.bun"
ENV PATH="$BUN_INSTALL/bin:$PATH"

RUN ./scripts/build_binary.sh $SOLIDINVOICE_VERSION
