<?php

declare(strict_types=1);

/*
 * This file is part of SolidInvoice project.
 *
 * (c) Pierre du Plessis <open-source@solidworx.co>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace SolidInvoice\UserBundle\Tests\Migration;

use Doctrine\DBAL\Connection;
use PHPUnit\Framework\Attributes\Group;
use SolidInvoice\InstallBundle\Test\EnsureApplicationInstalled;
use SolidInvoice\UserBundle\Entity\User;
use SolidInvoice\UserBundle\Test\Factory\UserFactory;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Zenstruck\Foundry\Test\Factories;

#[Group('functional')]
final class TotpSecretColumnLengthTest extends KernelTestCase
{
    use EnsureApplicationInstalled;
    use Factories;

    public function testTotpSecretColumnHasSufficientLength(): void
    {
        /** @var Connection $conn */
        $conn = self::getContainer()->get('doctrine.dbal.default_connection');
        $sm = $conn->createSchemaManager();

        $columns = $sm->listTableColumns('users');

        self::assertArrayHasKey('totp_secret', $columns, 'Column totp_secret should exist in the users table');
        self::assertGreaterThanOrEqual(
            255,
            $columns['totp_secret']->getLength(),
            'totp_secret column length should be at least 255 to accommodate TOTP secrets generated by scheb/2fa-totp'
        );
    }

    public function testLongTotpSecretCanBePersisted(): void
    {
        // scheb/2fa-totp v8 generates base32-encoded secrets from 32 random bytes,
        // producing ~52-character strings — longer than the previous 45-char column limit.
        $longSecret = str_repeat('A', 52);

        $user = UserFactory::createOne(['companies' => [$this->company]]);

        /** @var \Doctrine\Persistence\ObjectManager $em */
        $em = self::getContainer()->get('doctrine')->getManager();

        $user->setTotpSecret($longSecret);
        $em->flush();
        $em->clear();

        $persisted = $em->find(User::class, $user->getId());
        self::assertNotNull($persisted);
        self::assertTrue($persisted->isTotpAuthenticationEnabled());
    }
}
