<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120830162152 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE client_status (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(125) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, deleted DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_2EA62EAF5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE clients ADD status_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE clients ADD CONSTRAINT FK_C82E746BF700BD FOREIGN KEY (status_id) REFERENCES client_status (id)");
        $this->addSql("CREATE INDEX IDX_C82E746BF700BD ON clients (status_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE clients DROP FOREIGN KEY FK_C82E746BF700BD");
        $this->addSql("DROP TABLE client_status");
        $this->addSql("ALTER TABLE clients DROP FOREIGN KEY FK_C82E746BF700BD");
        $this->addSql("DROP INDEX IDX_C82E746BF700BD ON clients");
        $this->addSql("ALTER TABLE clients DROP status_id");
    }
}
