<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130418193436 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE config_sections (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(125) NOT NULL, UNIQUE INDEX UNIQ_965EAD465E237E06 (name), INDEX IDX_965EAD46727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE config_sections ADD CONSTRAINT FK_965EAD46727ACA70 FOREIGN KEY (parent_id) REFERENCES config_sections (id)");
        $this->addSql("ALTER TABLE app_config ADD section_id INT DEFAULT NULL, DROP section");
        $this->addSql("ALTER TABLE app_config ADD CONSTRAINT FK_318942FCD823E37A FOREIGN KEY (section_id) REFERENCES config_sections (id)");
        $this->addSql("CREATE INDEX IDX_318942FCD823E37A ON app_config (section_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE config_sections DROP FOREIGN KEY FK_965EAD46727ACA70");
        $this->addSql("ALTER TABLE app_config DROP FOREIGN KEY FK_318942FCD823E37A");
        $this->addSql("DROP TABLE config_sections");
        $this->addSql("DROP INDEX IDX_318942FCD823E37A ON app_config");
        $this->addSql("ALTER TABLE app_config ADD section VARCHAR(125) NOT NULL, DROP section_id");
    }
}
