<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130107202117 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("INSERT INTO `roles` (`id`, `name`, `role`) VALUES
                        (1, 'super_admin', 'ROLE_SUPER_ADMIN'),
                        (2, 'admin', 'ROLE_ADMIN'),
                        (3, 'client', 'ROLE_CLIENT'),
                        (4, 'user', 'ROLE_USER')");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("TRUNCATE TABLE `roles`");
    }
}
