<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130423105647 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE quotes CHANGE discount discount DOUBLE PRECISION DEFAULT NULL");
        $this->addSql("ALTER TABLE invoices CHANGE discount discount DOUBLE PRECISION DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE invoices CHANGE discount discount DOUBLE PRECISION NOT NULL");
        $this->addSql("ALTER TABLE quotes CHANGE discount discount DOUBLE PRECISION NOT NULL");
    }
}
