[
    "en", # English
    "af", # Afrikaans
    "ar", # Arabic
    "ca", # Catalan
    "zh-CN", # Chinese Simplified
    "zh-TW", # Chinese Traditional
    "cs", # Czech
    "da", # Danish
    "nl", # Dutch
    "fi", # Finnish
    "fr", # French
    "de", # German
    "el", # Greek
    "he", # Hebrew
    "hu", # Hungarian
    "it", # Italian
    "ja", # Japanese
    "ko", # Korean
    "no", # Norwegian
    "pl", # Polish
    "pt-PT", # Portuguese
    "pt-BR", # Portuguese, Brazilian
    "ro", # Romanian
    "ru", # Russian
    "sr", # Serbian (Cyrillic)
    "es-ES", # Spanish
    "sv-SE", # Swedish
    "tr", # Turkish
    "uk", # Ukrainian
    "vi", # Vietnamese
]
