parameters:
    env(mailer_transport): 'sendmail'
    env(mailer_host): '127.0.0.1'
    env(mailer_user): ~
    env(mailer_password): ~
    env(mailer_port): ~
    env(mailer_encryption): ~

    env(locale): 'en'
    env(secret): 'SecretToken'

    env(installed): ~

    env(SENTRY_DSN): ~
    env(SENTRY_SEND_DEFAULT_PII): false
    env(MAILER_DSN): 'null://null'
    env(SOLIDINVOICE_ALLOW_REGISTRATION): '0'

services:
    Monolog\Processor\PsrLogMessageProcessor:
        tags: { name: monolog.processor, handler: sentry }
