_api_keys_index:
    path: /profile/api
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\ApiIndex' }
    options:
        expose: true

_api_keys_xhr:
    resource: '@SolidInvoiceUserBundle/Resources/config/routing/ajax.yml'
    prefix: /profile/api/xhr
    options:
        expose: true

_users_list:
    path: /users
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\Users' }

_user_invite:
    path: /users/invite
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\InviteUser' }

_user_resend_invite:
    path: /users/invite/{id}/resend
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\ResendUserInvite' }
    options:
        expose: true

_user_delete_invite:
    path: /users/invite/delete
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\Grid\DeleteInvitations' }
    options:
        expose: true

_user_accept_invite:
    path: /invite/accept/{id}
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\AcceptInvitation' }

_user_edit:
    path: /users/edit/{id}
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\EditUser' }
    options:
        expose: true
    requirements:
        id: \d+

_users_grid:
    resource: '@SolidInvoiceUserBundle/Action/Grid'
    type: grid

_login:
    path: /login
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\Security\Login' }

_register:
    path: /register
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\Register' }

_logout:
    path: /logout

_login_check:
    path: /login-check

_user_forgot_password:
    path: /forgot-password
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\ForgotPassword\Request' }

_user_forgot_password_send_emal:
    path: /forgot-password/send
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\ForgotPassword\Send' }

_user_forgot_password_check_email:
    path: /forgot-password/check
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\ForgotPassword\Check' }

_user_password_reset:
    path: /forgot-password/reset/{token}
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\ForgotPassword\Reset' }

_profile:
    path: /profile
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\Profile' }

_edit_profile:
    path: /profile/edit
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\EditProfile' }

_change_password:
    path: /profile/change-password
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\Security\ChangePassword' }
