services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $installed: '%env(installed)%'

    Doctrine\Migrations\DependencyFactory: '@doctrine.migrations.dependency_factory'

    SolidInvoice\InstallBundle\Installer\Database\Migration:
        arguments:
            - '@doctrine.migrations.dependency_factory'

    SolidInvoice\InstallBundle\Command\InstallCommand: ~

    SolidInvoice\InstallBundle\Twig\Extension\InstallationExtension: ~
