services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $installed: '%env(installed)%'

    SolidInvoice\InstallBundle\Installer\Database\Migration:
        arguments: ['@filesystem', '@service_container']

    SolidInvoice\InstallBundle\Command\InstallCommand: ~
