{{- if and .Values.install.enabled (not .Values.install.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "solidinvoice.fullname" . }}-install
  labels:
    {{- include "solidinvoice.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
type: Opaque
stringData:
  ADMIN_EMAIL: {{ .Values.install.adminEmail | quote }}
  ADMIN_PASSWORD: {{ .Values.install.adminPassword | quote }}
{{- end }}
