services:

    _defaults:
        autowire: true
        autoconfigure: true

    SolidInvoice\SettingsBundle\SystemConfig:
        arguments:
            $installed: '%env(installed)%'
        lazy: true

    settings:
        alias: SolidInvoice\SettingsBundle\SystemConfig
        public: true

    SolidInvoice\SettingsBundle\Repository\SettingsRepository: ~
