<?php

declare(strict_types=1);

/*
 * This file is part of SolidInvoice project.
 *
 * (c) Pierre du Plessis <open-source@solidworx.co>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace SolidInvoice\DataGridBundle\Tests\GridBuilder\Column;

use InvalidArgumentException;
use PHPUnit\Framework\TestCase;
use SolidInvoice\DataGridBundle\GridBuilder\Column\StringColumn;
use SolidInvoice\DataGridBundle\GridBuilder\Filter\ChoiceFilter;
use Symfony\Component\Translation\TranslatableMessage;

/**
 * Tests for the Column base class functionality using StringColumn as concrete implementation.
 *
 * @covers \SolidInvoice\DataGridBundle\GridBuilder\Column\Column
 */
final class ColumnTest extends TestCase
{
    private StringColumn $column;

    protected function setUp(): void
    {
        $this->column = StringColumn::new('test_field');
    }

    public function testGetFieldReturnsConstructorValue(): void
    {
        self::assertSame('test_field', $this->column->getField());
    }

    public function testGetLabelReturnsAutoGeneratedLabel(): void
    {
        $label = $this->column->getLabel();
        self::assertInstanceOf(TranslatableMessage::class, $label);
        self::assertSame('Test Field', (string) $label);
    }

    public function testGetLabelReturnsCustomLabel(): void
    {
        $this->column->label('Custom Label');
        $label = $this->column->getLabel();
        self::assertInstanceOf(TranslatableMessage::class, $label);
        self::assertSame('Custom Label', (string) $label);
    }

    public function testGetLabelWithTranslatableInterface(): void
    {
        $translatable = new TranslatableMessage('translatable.key');
        $this->column->label($translatable);
        self::assertSame($translatable, $this->column->getLabel());
    }

    public function testIsSortableByDefault(): void
    {
        self::assertTrue($this->column->isSortable());
    }

    public function testSortableCanBeDisabled(): void
    {
        $this->column->sortable(false);
        self::assertFalse($this->column->isSortable());
    }

    public function testSortableCanBeReEnabled(): void
    {
        $this->column->sortable(false);
        $this->column->sortable(true);
        self::assertTrue($this->column->isSortable());
    }

    public function testGetSortableFieldReturnsFieldByDefault(): void
    {
        self::assertSame('test_field', $this->column->getSortableField());
    }

    public function testGetSortableFieldReturnsCustomField(): void
    {
        $this->column->sortableField('custom_sort_field');
        self::assertSame('custom_sort_field', $this->column->getSortableField());
    }

    public function testIsSearchableByDefault(): void
    {
        self::assertTrue($this->column->isSearchable());
    }

    public function testSearchableCanBeDisabled(): void
    {
        $this->column->searchable(false);
        self::assertFalse($this->column->isSearchable());
    }

    public function testGetFilterReturnsNullByDefault(): void
    {
        self::assertNull($this->column->getFilter());
    }

    public function testFilterSetsAndGetsCorrectly(): void
    {
        $filter = ChoiceFilter::new('status', ['a' => 'A']);
        $this->column->filter($filter);
        self::assertSame($filter, $this->column->getFilter());
    }

    public function testFormatValueReturnsIdentityByDefault(): void
    {
        $formatter = $this->column->getFormatValue();
        self::assertSame('test value', $formatter('test value'));
        self::assertSame(123, $formatter(123));
        self::assertNull($formatter(null));
    }

    public function testFormatValueSetsCustomFormatter(): void
    {
        $this->column->formatValue(static fn (mixed $value) => strtoupper((string) $value));
        $formatter = $this->column->getFormatValue();
        self::assertSame('TEST', $formatter('test'));
    }

    public function testGetLinkReturnsNullByDefault(): void
    {
        self::assertNull($this->column->getLink());
    }

    public function testLinkToSetsUrlLink(): void
    {
        $this->column->linkTo('https://example.com');
        self::assertSame('https://example.com', $this->column->getLink());
    }

    public function testGetLinkRouteReturnsNullByDefault(): void
    {
        self::assertNull($this->column->getLinkRoute());
        self::assertSame([], $this->column->getLinkParameters());
    }

    public function testLinkToRouteSetsRouteLink(): void
    {
        $this->column->linkToRoute('client_view', ['id' => 'id']);
        self::assertSame('client_view', $this->column->getLinkRoute());
        self::assertSame(['id' => 'id'], $this->column->getLinkParameters());
    }

    public function testLinkToRouteWithDefaultParameters(): void
    {
        $this->column->linkToRoute('client_view');
        self::assertSame('client_view', $this->column->getLinkRoute());
        self::assertSame([], $this->column->getLinkParameters());
    }

    public function testLinkToThrowsExceptionIfRouteLinkAlreadySet(): void
    {
        $this->column->linkToRoute('some_route');

        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Route link is already set for column test_field');
        $this->column->linkTo('https://example.com');
    }

    public function testLinkToRouteThrowsExceptionIfUrlLinkAlreadySet(): void
    {
        $this->column->linkTo('https://example.com');

        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Link is already set for column test_field');
        $this->column->linkToRoute('some_route');
    }

    public function testGetCellClassReturnsNullByDefault(): void
    {
        self::assertNull($this->column->getCellClass());
    }

    public function testCellClassSetsAndGetsCorrectly(): void
    {
        $this->column->cellClass('col-money');
        self::assertSame('col-money', $this->column->getCellClass());
    }

    public function testFluentInterface(): void
    {
        $filter = ChoiceFilter::new('test', ['a' => 'A']);

        $result = $this->column
            ->label('Test Label')
            ->sortable(true)
            ->sortableField('sort_field')
            ->searchable(false)
            ->filter($filter)
            ->cellClass('col-test')
            ->formatValue(static fn ($v) => $v);

        self::assertSame($this->column, $result);
    }

    public function testAutoGeneratedLabelHandlesSnakeCase(): void
    {
        $column = StringColumn::new('created_at');
        $label = $column->getLabel();
        self::assertInstanceOf(TranslatableMessage::class, $label);
        self::assertSame('Created At', $label->getMessage());
    }

    public function testAutoGeneratedLabelHandlesCamelCase(): void
    {
        $column = StringColumn::new('createdAt');
        $label = $column->getLabel();
        self::assertInstanceOf(TranslatableMessage::class, $label);
        // The snake() function converts camelCase to snake_case first
        self::assertSame('Created At', $label->getMessage());
    }
}
