name: "Release"

on:
  push:
    tags:
      - "*"

env:
  SOLIDINVOICE_ENV: prod
  SOLIDINVOICE_DEBUG: 0

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for actions/create-release to create a release
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: FranzDiebold/github-env-vars-action@1791216cd180e6578dd1d67fb8d2852b883a5f53

      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
         path: solidinvoice

      - name: Install PHP
        uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198
        with:
          coverage: none
          extensions: curl, gd, intl, opcache, json, openssl, pdo, soap, xsl, :xdebug
          ini-values: memory_limit=-1
          php-version: 8.3

      - name: Install PHP dependencies
        run: composer install --ansi --no-interaction --no-progress --no-suggest --prefer-dist --no-dev -o -a
        working-directory: solidinvoice

      - uses: oven-sh/setup-bun@v1

      - name: Set ENV Variables
        run: |
          echo SOLIDINVOICE_ENV=$SOLIDINVOICE_ENV > .env
          echo SOLIDINVOICE_DEBUG=$SOLIDINVOICE_DEBUG >> .env
        working-directory: solidinvoice

      - name: Install JS dependencies
        run: bun install
        working-directory: solidinvoice

      - name: Build Assets
        run: bun run build
        working-directory: solidinvoice

      - name: Cleanup files
        run: rm -Rf node_modules vendor-bin .github .git
        working-directory: solidinvoice

      - name: Create release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.CI_REF_NAME }}
          draft: true
          body: TODO

      - name: Create ZIP distribution
        run: zip -r SolidInvoice-${{ env.CI_REF_NAME }}.zip ./

      - name: List files
        run: ls -la

      - name: Upload ZIP distribution
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./SolidInvoice-${{ env.CI_REF_NAME }}.zip
            asset_name: SolidInvoice-${{ env.CI_REF_NAME }}.zip
            asset_content_type: application/zip

      - name: Delete ZIP File
        run: rm -Rf SolidInvoice-${{ env.CI_REF_NAME }}.zip

      - name: Create TAR distribution
        run: tar -zcvf SolidInvoice-${{ env.CI_REF_NAME }}.tar.gz ./solidinvoice

      - name: Upload TAR distribution
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./SolidInvoice-${{ env.CI_REF_NAME }}.tar.gz
            asset_name: SolidInvoice-${{ env.CI_REF_NAME }}.tar.gz
            asset_content_type: application/gzip

      - name: Delete TAR File
        run: rm -Rf SolidInvoice-${{ env.CI_REF_NAME }}.tar.gz
