name: Security Checker

on: [ pull_request ]

jobs:
  security-checker:
    name: Symfony Security Checker

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.4.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - uses: actions/checkout@v3
      - uses: symfonycorp/security-checker-action@v4

