name: Security Checker

on: [ pull_request ]

jobs:
  security-checker:
    name: Symfony Security Checker

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c8454efe5d0bdefd25384362fe217428ca277d57
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - uses: symfonycorp/security-checker-action@258311ef7ac571f1310780ef3d79fc5abef642b5

