name: Security Checker

on: [ pull_request ]

jobs:
  security-checker:
    name: Symfony Security Checker

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: symfonycorp/security-checker-action@258311ef7ac571f1310780ef3d79fc5abef642b5

