name: Security Checker

on: [ pull_request ]

jobs:
  security-checker:
    name: Symfony Security Checker

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: symfonycorp/security-checker-action@bb5092fdb50d4b92d301885fb6d0b0a41cea7bcd

